## Tables and Data Source setup

In [1]:
using ODBC
using DataFrames
using DSWB
using Formatting
using URIParser
using JSON

dsn = "dswb-natgeo" # Redshift esetTable(tableRt, tableType = "RESOURCE_TABLE")ndpoint
table = "beacons_4744" # beacon table name
tableRt = "beacons_4744_rt"

# Connect to Beacon Data
setRedshiftEndpoint(dsn)
setTable(table)
setTable(tableRt, tableType = "RESOURCE_TABLE")
;

Redshift endpoint set: 2017-06-06T13:34:36

In [2]:
# Packages

#include("/data/notebook_home/Production/Lib/Include-Package-v1.0.jl")

include("https://github.com/ChrisDavisNGP/NGP-DSWB/Lib/Include-Package-v2.0.jl")
#include_string("https://github.com/ChrisDavisNGP/NGP-DSWB/Lib/Include-Package-v2.0.jl")
#include_dependency("https://github.com/ChrisDavisNGP/NGP-DSWB/Lib/Include-Package-v2.0.jl")
;
# tv structure created in include above, so init time here
#timeVariables(2017,5,9,16,0,2017,5,9,16,59)
weeklyTimeVariables(days=7)
#yesterdayTimeVariables()
;

LoadError: could not open file /data/notebook_home/Production/Studies/Sessions/https:/github.com/ChrisDavisNGP/NGP-DSWB/Lib/Include-Package-v2.0.jl

In [12]:
LOAD_PATH

3-element Array{ByteString,1}:
 "/julia-ae26b25d43/local/share/julia/site/v0.4"
 "/julia-ae26b25d43/share/julia/site/v0.4"
 "/home/ubuntu/datascienceworkbench/lib/Modules/"

In [3]:
# Packages

include("/data/notebook_home/Production/Bodies/Individual-Streamline-v1.2.jl")

#pageGroup = "%"
pageGroup = "%"
urlRegEx = "%"
urlFull = "%"
#top10 = 10
top10 = 250
samplesMin = 10
sizeMin = 10000
#sizeMin = 0
#samplesMin = 0
usePageLoad=false
#lowerLimitMs = 1000
#upperLimitMs = 600000
lowerLimitMs = 2000.0
upperLimitMs = 60000.0
orderBy = "size"
#upperLimitMs = 120000.0
#orderBy = "time"
deviceType = ""

UP = UrlParams(table,tableRt,pageGroup,urlRegEx,urlFull,lowerLimitMs,upperLimitMs,top10,samplesMin,sizeMin,orderBy,usePageLoad,deviceType)

showJson=false
showDesktop=false
showMobile=true
showDevView=false
showCriticalPathOnly=true
showDebug=false
showDebugLevel = 0   # Tests use even numbers with > tests, make this an odd number or zero

SP = ShowParams(showDesktop,showMobile,showDevView,showCriticalPathOnly,showDebug,showDebugLevel)
;

In [4]:
SP.mobile = true
SP.desktop = false
UP.orderBy = "time"
if (SP.mobile)
    UP.deviceType = "mobile"
else
    UP.deviceType = "desktop"
end

urlListDF = returnMatchingUrlTableV2(TV,UP)
if (SP.debugLevel > 4)
    beautifyDF(urlListDF[1:min(3,end),:])
end

newListDF = urlListDF[Bool[x > UP.samplesMin for x in urlListDF[:cnt]],:]
topUrlList = newListDF[:urlgroup]
topUrls = cleanupTopUrlTable(topUrlList)
if (SP.debugLevel > 8)
    println(topUrls)
end
;

In [5]:
finalUrlTableOutput(TV,UP,SP,topUrls)
;

HTML{UTF8String}("    <table  class=\"dataframe-table\">\n    <thead><tr><th class=\"cell-1\" style=\"\">Recent Urls (Sorted By Time Descending; Min Samples  10 ; Top  250  Page Views)</th> <th class=\"cell-2\" style=\"\">Time</th> <th class=\"cell-3\" style=\"\">Request Made</th> <th class=\"cell-4\" style=\"\">Page Size</th> <th class=\"cell-5\" style=\"\">Samples</th></tr></thead>\n    <tbody>\n    <tr><td class=\"cell-1\" style=\"\">/m.yourshot.nationalgeographic.com/stories/empathy-gap/%</td> <td class=\"cell-2\" style=\"text-align:right;\">27,356</td> <td class=\"cell-3\" style=\"text-align:right;\">53</td> <td class=\"cell-4\" style=\"text-align:right;\">110,410</td> <td class=\"cell-5\" style=\"text-align:right;\">117</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/ocean.nationalgeographic.com/ocean/photos/deep-sea-creatures/%</td> <td class=\"cell-2\" style=\"text-align:right;\">25,639</td> <td class=\"cell-3\" style=\"text-align:right;\">82</td> <td class=\"cell-4\" style=\"text-align:right;\">238,060</td> <td class=\"cell-5\" style=\"text-align:right;\">927</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/03/sponsor-content-samsung-follow-me-to-cuba/%</td> <td class=\"cell-2\" style=\"text-align:right;\">25,199</td> <td class=\"cell-3\" style=\"text-align:right;\">81</td> <td class=\"cell-4\" style=\"text-align:right;\">934,150</td> <td class=\"cell-5\" style=\"text-align:right;\">662</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/magazine/2017/06/nodosaur-3d-interactive-dinosaur-fossil/%</td> <td class=\"cell-2\" style=\"text-align:right;\">25,116</td> <td class=\"cell-3\" style=\"text-align:right;\">107</td> <td class=\"cell-4\" style=\"text-align:right;\">18,193,579</td> <td class=\"cell-5\" style=\"text-align:right;\">873</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/m.yourshot.nationalgeographic.com/stories/cities-black-and-white/%</td> <td class=\"cell-2\" style=\"text-align:right;\">22,830</td> <td class=\"cell-3\" style=\"text-align:right;\">86</td> <td class=\"cell-4\" style=\"text-align:right;\">102,909</td> <td class=\"cell-5\" style=\"text-align:right;\">828</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/endangered_speciesact/%</td> <td class=\"cell-2\" style=\"text-align:right;\">22,480</td> <td class=\"cell-3\" style=\"text-align:right;\">91</td> <td class=\"cell-4\" style=\"text-align:right;\">1,021,772</td> <td class=\"cell-5\" style=\"text-align:right;\">318</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/sea-lion-drags-girl-feeding-behavior/%</td> <td class=\"cell-2\" style=\"text-align:right;\">21,584</td> <td class=\"cell-3\" style=\"text-align:right;\">87</td> <td class=\"cell-4\" style=\"text-align:right;\">898,155</td> <td class=\"cell-5\" style=\"text-align:right;\">10,117</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/m.yourshot.nationalgeographic.com/stories/minimalism/%</td> <td class=\"cell-2\" style=\"text-align:right;\">21,277</td> <td class=\"cell-3\" style=\"text-align:right;\">119</td> <td class=\"cell-4\" style=\"text-align:right;\">1,138,271</td> <td class=\"cell-5\" style=\"text-align:right;\">169</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/travel/features/best-food-cities-2017/%</td> <td class=\"cell-2\" style=\"text-align:right;\">20,372</td> <td class=\"cell-3\" style=\"text-align:right;\">87</td> <td class=\"cell-4\" style=\"text-align:right;\">909,400</td> <td class=\"cell-5\" style=\"text-align:right;\">64</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/killer-whale-attacks-blue-whale-monterey-drone-video/%</td> <td class=\"cell-2\" style=\"text-align:right;\">20,217</td> <td class=\"cell-3\" style=\"text-align:right;\">94</td> <td class=\"cell-4\" style=\"text-align:right;\">837,924</td> <td class=\"cell-5\" style=\"text-align:right;\">20,892</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/environment/global-warming/pollution/%</td> <td class=\"cell-2\" style=\"text-align:right;\">20,068</td> <td class=\"cell-3\" style=\"text-align:right;\">80</td> <td class=\"cell-4\" style=\"text-align:right;\">882,592</td> <td class=\"cell-5\" style=\"text-align:right;\">402</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/soviet-space-shuttle-kazakhstan-film-science/%</td> <td class=\"cell-2\" style=\"text-align:right;\">20,001</td> <td class=\"cell-3\" style=\"text-align:right;\">88</td> <td class=\"cell-4\" style=\"text-align:right;\">1,037,837</td> <td class=\"cell-5\" style=\"text-align:right;\">428</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/travel/lists/beautiful-mosques-around-the-world/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,856</td> <td class=\"cell-3\" style=\"text-align:right;\">83</td> <td class=\"cell-4\" style=\"text-align:right;\">924,369</td> <td class=\"cell-5\" style=\"text-align:right;\">2,720</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/m.yourshot.nationalgeographic.com/stories/saving-our-oceans/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,818</td> <td class=\"cell-3\" style=\"text-align:right;\">135</td> <td class=\"cell-4\" style=\"text-align:right;\">1,464,652</td> <td class=\"cell-5\" style=\"text-align:right;\">222</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/environment/global-warming/global-warming-effects/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,694</td> <td class=\"cell-3\" style=\"text-align:right;\">83</td> <td class=\"cell-4\" style=\"text-align:right;\">897,238</td> <td class=\"cell-5\" style=\"text-align:right;\">587</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/environment/global-warming/global-warming-causes/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,686</td> <td class=\"cell-3\" style=\"text-align:right;\">85</td> <td class=\"cell-4\" style=\"text-align:right;\">1,372,098</td> <td class=\"cell-5\" style=\"text-align:right;\">322</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2016/07/whales-death-grief-animals-science/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,653</td> <td class=\"cell-3\" style=\"text-align:right;\">86</td> <td class=\"cell-4\" style=\"text-align:right;\">906,492</td> <td class=\"cell-5\" style=\"text-align:right;\">3,065</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/animals/mammals/b/blue-whale/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,557</td> <td class=\"cell-3\" style=\"text-align:right;\">85</td> <td class=\"cell-4\" style=\"text-align:right;\">983,495</td> <td class=\"cell-5\" style=\"text-align:right;\">391</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/animals/mammals/g/giraffe/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,490</td> <td class=\"cell-3\" style=\"text-align:right;\">77</td> <td class=\"cell-4\" style=\"text-align:right;\">897,117</td> <td class=\"cell-5\" style=\"text-align:right;\">4,086</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/news/2010/04/100428-noahs-ark-found-in-turkey-science-religion-culture/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,472</td> <td class=\"cell-3\" style=\"text-align:right;\">91</td> <td class=\"cell-4\" style=\"text-align:right;\">979,241</td> <td class=\"cell-5\" style=\"text-align:right;\">623</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/archaeology-and-history/archaeology/fountain-of-youth/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,402</td> <td class=\"cell-3\" style=\"text-align:right;\">94</td> <td class=\"cell-4\" style=\"text-align:right;\">967,354</td> <td class=\"cell-5\" style=\"text-align:right;\">400</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/environment/global-warming/deforestation/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,391</td> <td class=\"cell-3\" style=\"text-align:right;\">84</td> <td class=\"cell-4\" style=\"text-align:right;\">980,448</td> <td class=\"cell-5\" style=\"text-align:right;\">506</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/phenomena.nationalgeographic.com/2015/08/19/whos-the-first-person-in-history-whose-name-we-know/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,210</td> <td class=\"cell-3\" style=\"text-align:right;\">154</td> <td class=\"cell-4\" style=\"text-align:right;\">6,030,834</td> <td class=\"cell-5\" style=\"text-align:right;\">1,262</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/travel/destinations/asia/india/should-women-travel-solo-india-tips/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,147</td> <td class=\"cell-3\" style=\"text-align:right;\">85</td> <td class=\"cell-4\" style=\"text-align:right;\">993,545</td> <td class=\"cell-5\" style=\"text-align:right;\">677</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2016/03/you-and-almost-everyone-you-know-owe-your-life-to-this-man/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,077</td> <td class=\"cell-3\" style=\"text-align:right;\">80</td> <td class=\"cell-4\" style=\"text-align:right;\">895,937</td> <td class=\"cell-5\" style=\"text-align:right;\">337</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/news/2014/01/140127-cats-pets-animals-nation-dogs-people-science/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,046</td> <td class=\"cell-3\" style=\"text-align:right;\">92</td> <td class=\"cell-4\" style=\"text-align:right;\">975,299</td> <td class=\"cell-5\" style=\"text-align:right;\">477</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/phenomena.nationalgeographic.com/2013/10/30/heres-what-happens-when-a-tick-bites-you/%</td> <td class=\"cell-2\" style=\"text-align:right;\">19,032</td> <td class=\"cell-3\" style=\"text-align:right;\">155</td> <td class=\"cell-4\" style=\"text-align:right;\">4,801,922</td> <td class=\"cell-5\" style=\"text-align:right;\">924</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/animals/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,824</td> <td class=\"cell-3\" style=\"text-align:right;\">79</td> <td class=\"cell-4\" style=\"text-align:right;\">923,034</td> <td class=\"cell-5\" style=\"text-align:right;\">16,833</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/travel.nationalgeographic.com/photographer-of-the-year-2017/gallery/week-4-nature/14%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,760</td> <td class=\"cell-3\" style=\"text-align:right;\">82</td> <td class=\"cell-4\" style=\"text-align:right;\">360,234</td> <td class=\"cell-5\" style=\"text-align:right;\">317</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/amur-siberian-tiger-russia-release-video/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,746</td> <td class=\"cell-3\" style=\"text-align:right;\">90</td> <td class=\"cell-4\" style=\"text-align:right;\">822,793</td> <td class=\"cell-5\" style=\"text-align:right;\">898</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/rare-albino-orangutan-found-indonesia/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,740</td> <td class=\"cell-3\" style=\"text-align:right;\">91</td> <td class=\"cell-4\" style=\"text-align:right;\">1,011,415</td> <td class=\"cell-5\" style=\"text-align:right;\">680</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2016/05/160505-shipwreck-gown-dress-royal-discovery-texel-holland-clothing/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,719</td> <td class=\"cell-3\" style=\"text-align:right;\">88</td> <td class=\"cell-4\" style=\"text-align:right;\">908,461</td> <td class=\"cell-5\" style=\"text-align:right;\">4,542</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/magazine/2017/04/explore-garbage-wave/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,562</td> <td class=\"cell-3\" style=\"text-align:right;\">90</td> <td class=\"cell-4\" style=\"text-align:right;\">983,358</td> <td class=\"cell-5\" style=\"text-align:right;\">443</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/travel/travel-interests/arts-and-culture/ancient-sites-built-by-aliens/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,453</td> <td class=\"cell-3\" style=\"text-align:right;\">81</td> <td class=\"cell-4\" style=\"text-align:right;\">966,324</td> <td class=\"cell-5\" style=\"text-align:right;\">127</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/magazine/2017/06/famous-liars/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,430</td> <td class=\"cell-3\" style=\"text-align:right;\">91</td> <td class=\"cell-4\" style=\"text-align:right;\">994,962</td> <td class=\"cell-5\" style=\"text-align:right;\">374</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/photography/proof/2017/03/polar-bears-zoo/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,358</td> <td class=\"cell-3\" style=\"text-align:right;\">88</td> <td class=\"cell-4\" style=\"text-align:right;\">1,014,495</td> <td class=\"cell-5\" style=\"text-align:right;\">511</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/04/mastodons-americas-peopling-migrations-archaeology-science/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,275</td> <td class=\"cell-3\" style=\"text-align:right;\">83</td> <td class=\"cell-4\" style=\"text-align:right;\">953,137</td> <td class=\"cell-5\" style=\"text-align:right;\">540</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/mexican-red-knee-tarantula-molting-exoskeleton-video/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,213</td> <td class=\"cell-3\" style=\"text-align:right;\">90</td> <td class=\"cell-4\" style=\"text-align:right;\">813,560</td> <td class=\"cell-5\" style=\"text-align:right;\">2,659</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2016/07/animals-science-sex-mating-anglerfish/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,126</td> <td class=\"cell-3\" style=\"text-align:right;\">86</td> <td class=\"cell-4\" style=\"text-align:right;\">885,899</td> <td class=\"cell-5\" style=\"text-align:right;\">3,184</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/black-mamba-snake-deadly-venom-golf-course-south-africa-video/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,110</td> <td class=\"cell-3\" style=\"text-align:right;\">90</td> <td class=\"cell-4\" style=\"text-align:right;\">814,568</td> <td class=\"cell-5\" style=\"text-align:right;\">8,723</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/adventure/lists/long-weekend-adventures/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,090</td> <td class=\"cell-3\" style=\"text-align:right;\">72</td> <td class=\"cell-4\" style=\"text-align:right;\">965,232</td> <td class=\"cell-5\" style=\"text-align:right;\">234</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2016/07/animals-oldest-sponges-whales-fish/%</td> <td class=\"cell-2\" style=\"text-align:right;\">18,068</td> <td class=\"cell-3\" style=\"text-align:right;\">86</td> <td class=\"cell-4\" style=\"text-align:right;\">881,243</td> <td class=\"cell-5\" style=\"text-align:right;\">945</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/travel/destinations/europe/united-kingdom/scotland/12-reasons-to-go-scotland-now/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,970</td> <td class=\"cell-3\" style=\"text-align:right;\">85</td> <td class=\"cell-4\" style=\"text-align:right;\">28,222,890</td> <td class=\"cell-5\" style=\"text-align:right;\">376</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/ancient-slingshot-lethal-44-magnum-scotland/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,916</td> <td class=\"cell-3\" style=\"text-align:right;\">90</td> <td class=\"cell-4\" style=\"text-align:right;\">844,836</td> <td class=\"cell-5\" style=\"text-align:right;\">12,166</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/02/pictures-1917-immigration-ban-archive/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,872</td> <td class=\"cell-3\" style=\"text-align:right;\">76</td> <td class=\"cell-4\" style=\"text-align:right;\">924,415</td> <td class=\"cell-5\" style=\"text-align:right;\">451</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2016/05/160523-pictures-world-turtle-day-photo-ark/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,845</td> <td class=\"cell-3\" style=\"text-align:right;\">80</td> <td class=\"cell-4\" style=\"text-align:right;\">878,081</td> <td class=\"cell-5\" style=\"text-align:right;\">3,074</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/adventure/lists/biking/best-mountain-biking-towns/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,704</td> <td class=\"cell-3\" style=\"text-align:right;\">78</td> <td class=\"cell-4\" style=\"text-align:right;\">1,054,243</td> <td class=\"cell-5\" style=\"text-align:right;\">1,434</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/photography/proof/2017/05/reteti-orphan-elephants-vitale/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,648</td> <td class=\"cell-3\" style=\"text-align:right;\">77</td> <td class=\"cell-4\" style=\"text-align:right;\">1,281,562</td> <td class=\"cell-5\" style=\"text-align:right;\">1,436</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/travel/your-faces-of-the-world-photos/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,634</td> <td class=\"cell-3\" style=\"text-align:right;\">80</td> <td class=\"cell-4\" style=\"text-align:right;\">1,152,028</td> <td class=\"cell-5\" style=\"text-align:right;\">384</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/archaeology-and-history/archaeology/atlantis/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,612</td> <td class=\"cell-3\" style=\"text-align:right;\">90</td> <td class=\"cell-4\" style=\"text-align:right;\">985,404</td> <td class=\"cell-5\" style=\"text-align:right;\">508</td></tr>\n    \n    <tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/animals-anatomy-mating-ocean-sex/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,575</td> <td class=\"cell-3\" style=\"text-align:right;\">87</td> <td class=\"cell-4\" style=\"text-align:right;\">908,078</td> <td class=\"cell-5\" style=\"text-align:right;\">847</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/rare-cyclops-goat-born-india-video/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,557</td> <td class=\"cell-3\" style=\"text-align:right;\">91</td> <td class=\"cell-4\" style=\"text-align:right;\">922,532</td> <td class=\"cell-5\" style=\"text-align:right;\">1,640</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/news.nationalgeographic.com/2017/05/drone-footage-narwhal-tusk-mystery/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,450</td> <td class=\"cell-3\" style=\"text-align:right;\">90</td> <td class=\"cell-4\" style=\"text-align:right;\">864,832</td> <td class=\"cell-5\" style=\"text-align:right;\">552</td></tr>\n<tr><td class=\"cell-1\" style=\"\">/www.nationalgeographic.com/adventure/lists/best-adventures-2013/%</td> <td class=\"cell-2\" style=\"text-align:right;\">17,406</td> <td class=\"cell-3\" style=\"text-align:right;\">71</td> <td class=\"cel